### ISSUE TITLE
Error when adding new users manually on Demo site

### ISSUE THREAD

**Issue by duboisp** [gctools-hackathon-ircc/gcconnex#8]
```
hpmailerException Object
(
[message:protected] => Invalid address: 
[string:Exception:private] => exception 'phpmailerException' with message 'Invalid address: ' in /home/tbsh5/gcconnex/mod/phpmailer/vendors/class.phpmailer.php:521
Stack trace:
#0 /home/tbsh5/gcconnex/mod/phpmailer/start.php(144): PHPMailer->SetFrom(NULL, NULL)
#1 /home/tbsh5/gcconnex/mod/cp_notifications/start.php(451): phpmailer_send('eabby1981@yahoo...', 'abutu', 'You have been a...', '?<html>?<body>?...')
#2 [internal function]: cp_overwrite_notification_hook('cp_overwrite_no...', 'all', NULL, Array)
#3 /home/tbsh5/gcconnex/engine/classes/Elgg/PluginHooksService.php(38): call_user_func_array('cp_overwrite_no...', Array)
#4 /home/tbsh5/gcconnex/engine/lib/elgglib.php(777): Elgg\PluginHooksService->trigger('cp_overwrite_no...', 'all', Array, NULL)
#5 /home/tbsh5/gcconnex/mod/cp_notifications/actions/cp_notifications/useradd.php(70): elgg_trigger_plugin_hook('cp_overwrite_no...', 'all', Array)
#6 /home/tbsh5/gcconnex/engine/classes/Elgg/ActionsService.php(88): include('/home/tbsh5/gcc...')
#7 /home/tbsh5/gcconnex/engine/classes/Elgg/ActionsService.php(70): Elgg\ActionsService::includeFile('/home/tbsh5/gcc...')
#8 /home/tbsh5/gcconnex/engine/lib/actions.php(20): Elgg\ActionsService->execute('useradd')
#9 [internal function]: _elgg_action_handler(Array, 'action')
#10 /home/tbsh5/gcconnex/engine/classes/Elgg/Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')
#11 /home/tbsh5/gcconnex/index.php(63): Elgg\Router->route(Object(Elgg\Http\Request))
#12 {main}
[code:protected] => 0
[file:protected] => /home/tbsh5/gcconnex/mod/phpmailer/vendors/class.phpmailer.php
[line:protected] => 521
[trace:Exception:private] => Array
(
[0] => Array
(
[file] => /home/tbsh5/gcconnex/mod/phpmailer/start.php
[line] => 144
[function] => SetFrom
[class] => PHPMailer
[type] => ->
[args] => Array
(
[0] => 
[1] => 
)

)

[1] => Array
(
[file] => /home/tbsh5/gcconnex/mod/cp_notifications/start.php
[line] => 451
[function] => phpmailer_send
[args] => Array
(
[0] => eabby1981@yahoo.com
[1] => abutu
[2] => You have been added as a new user in GCconnex | Vous avez été ajouté en tant que nouvel utilisateur sur GCconnex
[3] => 
<html>
<body>
<!-- beginning of email template -->
<div width='100%' bgcolor='#fcfcfc'>
<div>
<div>

<!-- email header -->
<div align='center' width='100%' style='background-color:#f5f5f5; padding:20px 30px 15px 30px; font-family: sans-serif; font-size: 12px; color: #055959'>
This is a system-generated message from GCconnex. Please do not reply to this message | Ceci est un message généré par le système de GCconnex. Veuillez ne pas répondre à ce message
</div>


<!-- GCconnex banner -->
<div width='100%' style='padding: 0 0 0 10px; color:#ffffff; font-family: sans-serif; font-size: 35px; line-height:38px; font-weight: bold; background-color:#047177;'>
<span style='padding: 0 0 0 3px; font-size: 20px; color: #ffffff; font-family: sans-serif;'>GCconnex</span>
</div>


<!-- email divider -->
<div style='height:1px; background:#bdbdbd; border-bottom:1px solid #ffffff'></div>

<!-- english -->

<!-- main content of the notification (ENGLISH) -->
<!-- *optional* email message (DO NOT REPLY) -->
<div width='100%' style='padding:30px 30px 10px 30px; font-size:12px; line-height:22px; font-family:sans-serif;'>

<!-- The French Follows... -->
<span style='font-size:12px; font-weight: normal;'><i>(Le fran&ccedil;ais suit)</i></span><br/>

</div>



<div width='100%' style='padding:30px 30px 30px 30px; color:#153643; font-family:sans-serif; font-size:16px; line-height:22px; '>
<!-- TITLE OF CONTENT -->
<h4 style='padding: 0px 0px 5px 0px; font-family:sans-serif';>
<strong> You have been added as a new user in GCconnex </strong>
</h4>

<!-- BODY OF CONTENT -->

You can now log in using the following credentials <br/>
Username: abutu and Password: Newlife12

</div>
<div style='margin-top:15px; padding: 5px; color: #6d6d6d; border-bottom: 1px solid #ddd;'>
<div>Need help? <a href='http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/contactform/'>Contact us</a>.<br/>To unsubscribe from these notifications, login to GCconnex and edit your <a href='http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/settings/plugins/abutu/cp_notifications'>notifications' settings</a>.</div>
</div>

<!-- french -->

<!-- main content of the notification (FRENCH) -->
<div width='100%' style='padding:30px 30px 30px 30px; color:#153643; font-family:sans-serif; font-size:16px; line-height:22px;'>
<!-- TITLE OF CONTENT -->
<h4 style='padding: 0px 0px 5px 0px; font-family:sans-serif;'>
<strong> Vous avez été ajouté en tant que nouvel utilisateur sur GCconnex </strong>
</h4>

<!-- BODY OF CONTENT -->
Vous pouvez maintenant vous connecter en utilisant les informations de comptes suivants<br/>
Nom d'utilisateur : abutu et mot de passe : Newlife12

</div>
<div style='margin-top:15px; padding: 5px; color: #6d6d6d;'>
<div> Besoin d’aide? <a href='http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/mod/contactform/'>Contactez-nous</a>.<br/>Pour vous désabonner de ces notifications, connectez-vous à GCconnex et modifiez vos <a href='http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/settings/plugins/abutu/cp_notifications'>paramètres de notifications</a>.</div>
</div>

<!-- email divider -->
<div style='height:1px; background:#bdbdbd; border-bottom:1px solid #ffffff'></div>

<!-- email footer -->
<div align='center' width='100%' style='background-color:#f5f5f5; padding:20px 30px 15px 30px; font-family: sans-serif; font-size: 16px; color: #055959'> </div>

</div>
</div>
</div>
</body>
</html>

)

)

[2] => Array
(
[function] => cp_overwrite_notification_hook
[args] => Array
(
[0] => cp_overwrite_notification
[1] => all
[2] => 
[3] => Array
(
[cp_user_name] => abutu
[cp_msg_type] => cp_useradd
[cp_site_name] => GC Connex for IRCC
[cp_site_url] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/
[cp_username] => abutu
[cp_password] => Newlife12
[cp_user] => ElggUser Object
(
[url_override:protected] => 
[icon_override:protected] => 
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 119
[type] => user
[subtype] => 0
[owner_guid] => 0
[site_guid] => 1
[container_guid] => 0
[access_id] => 2
[time_created] => 1491500222
[time_updated] => 1491500222
[last_action] => 1491500222
[enabled] => yes
[name] => abutu
[username] => abutu
[password] => 
[salt] => 
[password_hash] => $2y$10$bzoBEj0K0oV0K7qquGYanumPZbbSGO3OhvvQCSxWIL29iHVtp7zTa
[email] => eabby1981@yahoo.com
[language] => en
[banned] => no
[admin] => yes
[prev_last_action] => 0
[last_login] => 0
[prev_last_login] => 0
)

[valid:protected] => 
)

)

)

)

[3] => Array
(
[file] => /home/tbsh5/gcconnex/engine/classes/Elgg/PluginHooksService.php
[line] => 38
[function] => call_user_func_array
[args] => Array
(
[0] => cp_overwrite_notification_hook
[1] => Array
(
[0] => cp_overwrite_notification
[1] => all
[2] => 
[3] => Array
(
[cp_user_name] => abutu
[cp_msg_type] => cp_useradd
[cp_site_name] => GC Connex for IRCC
[cp_site_url] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/
[cp_username] => abutu
[cp_password] => Newlife12
[cp_user] => ElggUser Object
(
[url_override:protected] => 
[icon_override:protected] => 
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 119
[type] => user
[subtype] => 0
[owner_guid] => 0
[site_guid] => 1
[container_guid] => 0
[access_id] => 2
[time_created] => 1491500222
[time_updated] => 1491500222
[last_action] => 1491500222
[enabled] => yes
[name] => abutu
[username] => abutu
[password] => 
[salt] => 
[password_hash] => $2y$10$bzoBEj0K0oV0K7qquGYanumPZbbSGO3OhvvQCSxWIL29iHVtp7zTa
[email] => eabby1981@yahoo.com
[language] => en
[banned] => no
[admin] => yes
[prev_last_action] => 0
[last_login] => 0
[prev_last_login] => 0
)

[valid:protected] => 
)

)

)

)

)

[4] => Array
(
[file] => /home/tbsh5/gcconnex/engine/lib/elgglib.php
[line] => 777
[function] => trigger
[class] => Elgg\PluginHooksService
[type] => ->
[args] => Array
(
[0] => cp_overwrite_notification
[1] => all
[2] => Array
(
[cp_user_name] => abutu
[cp_msg_type] => cp_useradd
[cp_site_name] => GC Connex for IRCC
[cp_site_url] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/
[cp_username] => abutu
[cp_password] => Newlife12
[cp_user] => ElggUser Object
(
[url_override:protected] => 
[icon_override:protected] => 
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 119
[type] => user
[subtype] => 0
[owner_guid] => 0
[site_guid] => 1
[container_guid] => 0
[access_id] => 2
[time_created] => 1491500222
[time_updated] => 1491500222
[last_action] => 1491500222
[enabled] => yes
[name] => abutu
[username] => abutu
[password] => 
[salt] => 
[password_hash] => $2y$10$bzoBEj0K0oV0K7qquGYanumPZbbSGO3OhvvQCSxWIL29iHVtp7zTa
[email] => eabby1981@yahoo.com
[language] => en
[banned] => no
[admin] => yes
[prev_last_action] => 0
[last_login] => 0
[prev_last_login] => 0
)

[valid:protected] => 
)

)

[3] => 
)

)

[5] => Array
(
[file] => /home/tbsh5/gcconnex/mod/cp_notifications/actions/cp_notifications/useradd.php
[line] => 70
[function] => elgg_trigger_plugin_hook
[args] => Array
(
[0] => cp_overwrite_notification
[1] => all
[2] => Array
(
[cp_user_name] => abutu
[cp_msg_type] => cp_useradd
[cp_site_name] => GC Connex for IRCC
[cp_site_url] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/
[cp_username] => abutu
[cp_password] => Newlife12
[cp_user] => ElggUser Object
(
[url_override:protected] => 
[icon_override:protected] => 
[temp_metadata:protected] => Array
(
)

[temp_annotations:protected] => Array
(
)

[temp_private_settings:protected] => Array
(
)

[volatile:protected] => Array
(
)

[tables_split:protected] => 2
[tables_loaded:protected] => 2
[attributes:protected] => Array
(
[guid] => 119
[type] => user
[subtype] => 0
[owner_guid] => 0
[site_guid] => 1
[container_guid] => 0
[access_id] => 2
[time_created] => 1491500222
[time_updated] => 1491500222
[last_action] => 1491500222
[enabled] => yes
[name] => abutu
[username] => abutu
[password] => 
[salt] => 
[password_hash] => $2y$10$bzoBEj0K0oV0K7qquGYanumPZbbSGO3OhvvQCSxWIL29iHVtp7zTa
[email] => eabby1981@yahoo.com
[language] => en
[banned] => no
[admin] => yes
[prev_last_action] => 0
[last_login] => 0
[prev_last_login] => 0
)

[valid:protected] => 
)

)

)

)

[6] => Array
(
[file] => /home/tbsh5/gcconnex/engine/classes/Elgg/ActionsService.php
[line] => 88
[args] => Array
(
[0] => /home/tbsh5/gcconnex/mod/cp_notifications/actions/cp_notifications/useradd.php
)

[function] => include
)

[7] => Array
(
[file] => /home/tbsh5/gcconnex/engine/classes/Elgg/ActionsService.php
[line] => 70
[function] => includeFile
[class] => Elgg\ActionsService
[type] => ::
[args] => Array
(
[0] => /home/tbsh5/gcconnex/mod/cp_notifications/actions/cp_notifications/useradd.php
)

)

[8] => Array
(
[file] => /home/tbsh5/gcconnex/engine/lib/actions.php
[line] => 20
[function] => execute
[class] => Elgg\ActionsService
[type] => ->
[args] => Array
(
[0] => useradd
)

)

[9] => Array
(
[function] => _elgg_action_handler
[args] => Array
(
[0] => Array
(
[0] => useradd
)

[1] => action
)

)

[10] => Array
(
[file] => /home/tbsh5/gcconnex/engine/classes/Elgg/Router.php
[line] => 80
[function] => call_user_func
[args] => Array
(
[0] => _elgg_action_handler
[1] => Array
(
[0] => useradd
)

[2] => action
)

)

[11] => Array
(
[file] => /home/tbsh5/gcconnex/index.php
[line] => 63
[function] => route
[class] => Elgg\Router
[type] => ->
[args] => Array
(
[0] => Elgg\Http\Request Object
(
[attributes] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
)

)

[request] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_token] => aSXod9kAKGVa9kvygtiT1A
[__elgg_ts] => 1491500155
[name] => abutu
[username] => abutu
[email] => eabby1981@yahoo.com
[password] => Newlife12
[password2] => Newlife12
[admin] => Array
(
[0] => 1
)

)

)

[query] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[__elgg_uri] => action/useradd
)

)

[server] => Symfony\Component\HttpFoundation\ServerBag Object
(
[parameters:protected] => Array
(
[REDIRECT_no-gzip] => 1
[REDIRECT_dont-vary] => 1
[REDIRECT_STATUS] => 200
[HTTP_HOST] => tbshackathon5.canadaeast.cloudapp.azure.com
[HTTP_CONNECTION] => keep-alive
[CONTENT_LENGTH] => 170
[HTTP_CACHE_CONTROL] => max-age=0
[HTTP_ORIGIN] => http://tbshackathon5.canadaeast.cloudapp.azure.com
[HTTP_UPGRADE_INSECURE_REQUESTS] => 1
[HTTP_USER_AGENT] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
[CONTENT_TYPE] => application/x-www-form-urlencoded
[HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
[HTTP_REFERER] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/admin/users/add
[HTTP_ACCEPT_ENCODING] => gzip, deflate
[HTTP_ACCEPT_LANGUAGE] => en-GB,en;q=0.8,en-US;q=0.6,fr-CA;q=0.4,fr;q=0.2
[HTTP_COOKIE] => Elgg_install=reu19u84q303esba6qp5ilni03; Elgg=v982175e16fvv9o7otgbvgvna2
[PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[SERVER_SIGNATURE] => <address>Apache/2.4.7 (Ubuntu) Server at tbshackathon5.canadaeast.cloudapp.azure.com Port 80</address>

[SERVER_SOFTWARE] => Apache/2.4.7 (Ubuntu)
[SERVER_NAME] => tbshackathon5.canadaeast.cloudapp.azure.com
[SERVER_ADDR] => 10.0.19.8
[SERVER_PORT] => 80
[REMOTE_ADDR] => 207.107.76.118
[DOCUMENT_ROOT] => /var/www/html
[REQUEST_SCHEME] => http
[CONTEXT_PREFIX] => 
[CONTEXT_DOCUMENT_ROOT] => /var/www/html
[SERVER_ADMIN] => webmaster@localhost
[SCRIPT_FILENAME] => /var/www/html/gcconnex/index.php
[REMOTE_PORT] => 33985
[REDIRECT_QUERY_STRING] => __elgg_uri=action/useradd
[REDIRECT_URL] => /gcconnex/action/useradd
[GATEWAY_INTERFACE] => CGI/1.1
[SERVER_PROTOCOL] => HTTP/1.1
[REQUEST_METHOD] => POST
[QUERY_STRING] => __elgg_uri=action/useradd
[REQUEST_URI] => /gcconnex/action/useradd
[SCRIPT_NAME] => /gcconnex/index.php
[PHP_SELF] => /gcconnex/index.php
[REQUEST_TIME_FLOAT] => 1491500221.684
[REQUEST_TIME] => 1491500221
)

)

[files] => Symfony\Component\HttpFoundation\FileBag Object
(
[parameters:protected] => Array
(
)

)

[cookies] => Symfony\Component\HttpFoundation\ParameterBag Object
(
[parameters:protected] => Array
(
[Elgg_install] => reu19u84q303esba6qp5ilni03
[Elgg] => v982175e16fvv9o7otgbvgvna2
)

)

[headers] => Symfony\Component\HttpFoundation\HeaderBag Object
(
[headers:protected] => Array
(
[host] => Array
(
[0] => tbshackathon5.canadaeast.cloudapp.azure.com
)

[connection] => Array
(
[0] => keep-alive
)

[content-length] => Array
(
[0] => 170
)

[cache-control] => Array
(
[0] => max-age=0
)

[origin] => Array
(
[0] => http://tbshackathon5.canadaeast.cloudapp.azure.com
)

[upgrade-insecure-requests] => Array
(
[0] => 1
)

[user-agent] => Array
(
[0] => Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
)

[content-type] => Array
(
[0] => application/x-www-form-urlencoded
)

[accept] => Array
(
[0] => text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
)

[referer] => Array
(
[0] => http://tbshackathon5.canadaeast.cloudapp.azure.com/gcconnex/admin/users/add
)

[accept-encoding] => Array
(
[0] => gzip, deflate
)

[accept-language] => Array
(
[0] => en-GB,en;q=0.8,en-US;q=0.6,fr-CA;q=0.4,fr;q=0.2
)

[cookie] => Array
(
[0] => Elgg_install=reu19u84q303esba6qp5ilni03; Elgg=v982175e16fvv9o7otgbvgvna2
)

)

[cacheControl:protected] => Array
(
[max-age] => 0
)

)

[content:protected] => 
[languages:protected] => 
[charsets:protected] => 
[encodings:protected] => 
[acceptableContentTypes:protected] => 
[pathInfo:protected] => 
[requestUri:protected] => /gcconnex/action/useradd
[baseUrl:protected] => 
[basePath:protected] => 
[method:protected] => 
[format:protected] => 
[session:protected] => 
[locale:protected] => 
[defaultLocale:protected] => en
)

)

)

)

[previous:Exception:private] => 
)
```

**Comment by nschonni** [comment]
Because there is no email server setup on the VM/docker so the configuration is missing
